### ISSUE TITLE
attempting mass download of chat and chat2s

### ISSUE THREAD

**Issue by GhoulHound** [irsat000/CAI-Tools#10]
looking to download entire conversation history of multiple characters. i go to saved chats and try using any of the options but it only saves the new chat2 chats. it seems like the chat2s are the only ones the extension sees. im using firefox. will this be possible in the future?

thank you for working on this great extension! ive already been using the character card/profile downloading and that seems to work just fine!

**Comment by irsat000** [comment]
Yes, it is intentional. Chat2 histories for chat2 characters.

I can actually add old chats aswell, but there are two reasons why I won't.

1. Users will only continue using chat and no more normal conversations.

2. Character.ai devs must be trying to migrate chat2 now. That's a possibility.

3. The main reason, I am hella bussy.
