### ISSUE TITLE
CAI Tool download character functions not working.

### ISSUE THREAD

**Issue by RebotiK** [irsat000/CAI-Tools#11]
When I try to download a character using "Download Character" in Character tab, it only close the CAI Tool panel and doesn't do anything else, both json and png aren't working. But the download chat option and download example chat working normal.

**Comment by irsat000** [comment]
Thank you for the issue. I saw your review late at night, now I am going to work. When I come back, I will deal with it. See you soon!

**Comment by irsat000** [comment]
I tried on my phone using Kiwi browser and seems to be working both for old and new characters. This shows that the functions and metjods are still the same and there is no website update on those.

Just wanted to make sure, do you see a message like "Multiple downloads blocked" on top right? Seems unlikely since conversation works fine you said. 

Are you using Firefox? Could you give me more details, it's hard to fix when it's working on my machine.

**Comment by RebotiK** [comment]
There is no "Multiple downloads blocked" message appeared. I tried on 3 different browsers (Opera GX, Chrome and Firefox), all of them gave them same result. I'll try using my phone then.

**Comment by irsat000** [comment]
Nope, that shouldn't be the reason. The moment is saw the character's ID up there on the URL assigned with this charId=[ID], it should work.

I will make a better design if this was the cause.

**Comment by irsat000** [comment]
I just tried it with new characters and they worked totally fine. I got similar issues about empty chats, maybe there is something we are missing. I will check it out at home.

**Comment by RebotiK** [comment]
OK. Thank you.
