### ISSUE TITLE
Consecutive character chats are not saved when exported as Oobabooga or Tavern chat

### ISSUE THREAD

**Issue by FFaUniHan** [irsat000/CAI-Tools#14]
Hello! I'm Han. I've been using your chrome plugin for a while for saving my chat logs. Thank you so much for your work! It's very useful and save me a lot of time copy-pasting. 

I found a weird bug where if you save chatlogs as **Oobabooga** or **Tavern JSON** or just plain text **example chat**, **if your character spoke multiple times consecutively, none of those characters chats will be saved until the user spoke another line**. 

<img src="https://github.com/irsat000/CAI-Tools/assets/35650645/78750898-0df5-4f77-bfa4-0f9c16fc5c35" width="50%">
<img src="https://github.com/irsat000/CAI-Tools/assets/35650645/a246c4a0-96fb-439f-8f11-5950da7801b7" width="50%">
<img src="https://github.com/irsat000/CAI-Tools/assets/35650645/17984006-f207-4153-ad86-e3d38bfe00b7" width="50%">

This however, doesn't happen if you select to **save it from Chat History as HTM**L. Is this intentional?

<img src="https://github.com/irsat000/CAI-Tools/assets/35650645/91070bff-8980-46d0-9e5f-83aa0a75cef4" width="50%">
<img src="https://github.com/irsat000/CAI-Tools/assets/35650645/de403f9b-2366-470c-85bc-4f822effd7a9" width="50%">

Also I do notice that the last one or two chat won't be saved as well.

Once again, thank you for your work! I usually saved my chats as JSON and load it on my own HTML page where I can choose to display character image before the chat is loaded. Let me know if I can contribute that into this plugin as well!

**Comment by irsat000** [comment]
Oobabooga and Tavern don't support multiple messages back to back as far as I know. That's why I had to cut them off. Some people reported the user and character switches places at such encounters. Please let me know if that only applies one of them, Oobabooga or Tavern.

By the way, the realization just hit me. I could have just merged them into one message lol.

As for other question, I would like to read and answer them tomorrow.

**Comment by irsat000** [comment]
More detail about missing recent chats and your html page would be nice for tomorrow. Would save time for both of us.

**Comment by irsat000** [comment]
Alright, commit 45c42ef should solve the problem of consecutive messages. I merged the messages.

By last couple chats not saving, you mean history right? It downloads whatever the character.ai shows as the history. You see it in View Chat Histories and not in files?

Also if you opened the box, went back to conversation, saved and talked again, then came back to View Chat Histories, new chats won't appear because I keep it as "Ready" (Downloaded) for efficiency. It doesn't check again, you have to reload the page to repeat the process.

**Comment by FFaUniHan** [comment]
Damn, you reply it so fast! Yes, I can confirm that the new JSON file does combine multiple chats into one, which may not be ideal if I roleplay two characters at once against an AI. Is it possible for you to provide options to export as raw Tavern data? So every consecutive character chat will still be separated?

For the recent chat not saving, I can confirm that this is also fixed with the consecutive chats saving as single chat. I will keep testing this new update to see if there's any further error.

About my HTML page, right now it's taking Oobabooga JSON and adding in fields where I can assign names for the user and character, plus profile picture for both of them. I will probably change it to use Tavern JSONL tomorrow, because consecutive chats do mess up the ordering. Of course, it will be a nice addition to the offline HTML export feature in this plugin. My HTML is attached in this post.

[CharAI Chat Display.zip](https://github.com/irsat000/CAI-Tools/files/12541223/CharAI.Chat.Display.zip)

Sidenote: you're the fastest responding dev I've met in github so far! Keep up the good work! I wish I can contribute more, but my js is a bit rusty.

**Comment by irsat000** [comment]
I was quite late actually, I didn't receive a notification, but thank you.

Naturally I can't add a different download option for you only, BUT, I can help you replace offline reading with a commit. I liked the design and I was already thinking about improving mine. You can forget about JSON or JSONL imports, adding picture and names by hand. I could give you an example format right now;

```
{
    "charName": "",
    "charPic": "",
    "userName": "",
    "userPic": "",
    "messages": [
        {
            "isUser": false,
            "message": ""
        },
        {
            "isUser": true,
            "message": ""
        },
        {
            "isUser": false,
            "message": ""
        },
        {
            "isUser": false,
            "message": ""
        }
    ]
}
```
This should be enough. This can be inside an array so we can use it as history aswell, similar to mine. One option in chat page and one option in history page. It's easy, don't worry. What do you think?

**Comment by FFaUniHan** [comment]
Oh yes, I like this approach! That would be very nice middle ground! It maintains the clarity, where the options to export JSON are intended to continue it somewhere else, and the option to export it as offline copy would be for those to remember it. 

And yes, I can handle dark mode myself. Some plugin in my browser also have a way to "dark mode-ify" light mode.

**Comment by irsat000** [comment]
You don't seem new to programming, go ahead. For the basic concept, in this exact format, I am going to replace a string in the file before download. Like this;

`const historyData = '<WILL_BE_REPLACED';`

When we open the html, this changed constant will be read with JSON.parse(historyData) and applied to the page. It's an array so make sure to get the first array for initialization. I am saying all this because you said ypu are not very good with JS. You can always check out the current one's codes.

**Comment by irsat000** [comment]
Yes, I am going to prepare the history data. Each chat will be in the format I wrote, they will be wrapped in an array so it can be used as history. You can use the indexes to make a chat switcher, dropdown or anything you want. If the array's length is 1, make it so that the option won't show up, indicating this is a singular chat.

**Comment by irsat000** [comment]
It's pretty hard like this, do you have discord?

**Comment by FFaUniHan** [comment]
Yes, my discord is just my name: ffaunihan
