### ISSUE TITLE
Full duplicate not working

### ISSUE THREAD

**Issue by powerfulchris07** [irsat000/CAI-Tools#29]
when i do a full duplicate it only goes up to 411 messages and just freezes there

**Comment by irsat000** [comment]
I didn't get the chance to try it on bigger chats, the problem is most likely about Character.AI rejecting it at some point because it's just too much request. I might have to add a similar system to chat logs to continue from where it left off. That's the only solution for it.

For now please use last 100 messages. If you don't want to go back too far, it won't remember it anyway. I will fix it soon. I am currently working on a Firefox specific problem that prevents this feature to not work at all.

**Comment by powerfulchris07** [comment]
whoops i didnt mean to press that

**Comment by powerfulchris07** [comment]
i did this yesterday and i didnt see a completely red one when it crashed

**Comment by irsat000** [comment]
Ah, I see it's not a browser error which is red, it's a "mission failed successfully" error. The last message should still have everything I need, I hope you copied it. Sorry for the trouble.

**Comment by powerfulchris07** [comment]
{"command": "neo_error", "request_id": "64087a10-b44a-48e6-8e37-a35233d5f209", "comment": "not found: row not found(Table: Candidate, PrimaryKey: (\"1faf6942-7bdd-43a1-aef5-cdd94f5700b8\",\"cc5422c4-2fc1-400f-9894-bfef4c80321e\",\"cc5422c4-2fc1-400f-9894-bfef4c80321e\"))", "error_code": 404, "sub_code": null}

**Comment by irsat000** [comment]
Each message is associated with the message above. I believe a new message can't find the earlier message. I coded it a way that it would work like clock work.

Now I don't have a scenario for image generation. Perhaps it's because your chat has an image or something like that?

**Comment by irsat000** [comment]
Okay, I was looking at another chat duplication problem and found out why. New version will work, no worries. This can stay open for confirmation from you.

If you are curious, it's because back to back human reply breaks the chain of messages. Skill issue on my part in other words. Solved it now.

**Comment by irsat000** [comment]
Is it fixed?

**Comment by powerfulchris07** [comment]
my bad i forgot about this, no it hasnt been fixed and should i do this on the new or old site?

**Comment by powerfulchris07** [comment]
Yup it works now thanks for your help
