### ISSUE TITLE
Memory Manage throwing error

### ISSUE THREAD

**Issue by LeilanPAD** [irsat000/CAI-Tools#30]
Attempting to save a memory regardless of size using the Memory Manager gives the popup "Couldn't be saved, please report on github if you don't know the reason"

**Comment by irsat000** [comment]
Click F12, open the console, take a screenshot of the error messages.

It's probably caused by localStorage limit. Each site has a small limit for it and I am using that. I guess I need "storage" permission for a good amount of space for the extension's settings.

As a temporary solution, in the console, you can run `localStorage.clear()` code to clean Character.AI's storage. It doesn't hold anything important. Refresh the page and try again. If this solves it, please let me know.

**Comment by LeilanPAD** [comment]
would you get mad at me if i said the issue somehow fixed itself between yesterday and today
