### ISSUE TITLE
Issues related to chat duplication

### ISSUE THREAD

**Issue by Boraking98** [irsat000/CAI-Tools#36]
I duplicated an entire chat (there were about 700 messages) and it worked perfectly. However, after a few days, all duplicate chats were marked as 'edited' and some messages disappeared.

The deleted messages were not random. There were times when I press Enter without writing a message to the character to see the character's next reaction, but these messages have disappeared...

This happened to both the copy chat and the original chat. I am very confused...

The version I tried is Chrome

**Comment by irsat000** [comment]
The extension has no setting to change anything in previous chat. I get the chat the same way I get the others, then make a new chat, then populate it.

The reason they are edited is because I can't send message on behalf of the bot, so I wait for it to reply then edit it to match your previous chat. That's why it takes a long time.

Regarding the problem you are facing, if it happens in original chats, it's unlikely to be the extension's problem, especially if it worked the way it was intented as you said.

Could you test it around a bit and see if you can replicate it?

**Comment by Boraking98** [comment]
I was wrong about the previous chat-related changes. I apologize. However, the phenomenon of some messages being deleted from duplicate chats still persists. If you get a character's message by simply pressing Enter without entering a message, those chats will be deleted during the duplication process...

**Comment by irsat000** [comment]
Maybe I forgot that scenario, I will fix it if it's the case. Will be up with the new update.

**Comment by irsat000** [comment]
Yes I forgot that, or maybe they changed the way it worked, probably my fault. It doesn't delete the continued replies, it adds them as swipes! Bonkers.

**Comment by irsat000** [comment]
I fixed it, please wait for the next update.

**Comment by Boraking98** [comment]
It was an incredibly fast response, unexpectedly. Thank you for your work, service, and quick response, and I look forward to your next work. However, because of this incident, I lost one of my existing chats, which is a bit sad, but I hope this makes other people happier...

**Comment by irsat000** [comment]
Is it fixed now?

**Comment by Boraking98** [comment]
It works perfectly. thank you

**Comment by irsat000** [comment]
I am glad.
