### ISSUE TITLE
Pinned Message

### ISSUE THREAD

**Issue by owen555999** [irsat000/CAI-Tools#47]
Can you add the Pinned Message system to use more than the 5 times that Character.ai provides?

**Comment by irsat000** [comment]
![pinnedLimitReached](https://github.com/irsat000/CAI-Tools/assets/38238671/67f1e160-820a-41ba-b8e5-ee1dacc4f5b5)

I tested just now upon your and a review's requests. It's unfortunately not possible as you can see. It's secured safely on the back end. Good for them, sad for us.

**Comment by owen555999** [comment]
And if you create a separate Pinned Message yourself in an extension, is that possible?

**Comment by irsat000** [comment]
That's not how it works. Each chat has 5 pin limit and it only remembers the pins on that chat when preparing a reply. So if you had some other pin, which you can only get on other chats and not "in an extension", they would not remember that because it's not fed into the Large Language Model they use when responding.

**Comment by owen555999** [comment]
Ok. Thanks for the answer :)
