### ISSUE TITLE
Pinned Messages/Memories Conflict

### ISSUE THREAD

**Issue by chocobolodesk** [irsat000/CAI-Tools#59]
Sometimes when memories are deployed in a message, the bot will reply with a message relevant to the recently pinned messages rather than continuing on with the current scenario. 

Unpinning the relevant messages in question will resolve this;; the memories will deploy and the bot will then reply as normal, but it can get somewhat frustrating Dx

**Comment by irsat000** [comment]
There doesn't seem to be a real conflict, they all act normally. Pinned message have such an effect, that's why we pin them after all.

Since they are both trying to do a similar job, there could be some "conflict", but it's not programming related, I have no power over it. It just behaves how character.ai programmed it to behave.

Just one thing, I am planning on making a Memory Manager v2, this one will make it less cumbersome and potentially work better.
