### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by CashOver** [irsat000/CAI-Tools#64]
Hi, I would like to know how I could hide the messages when the Memory Manager is activated, or make them visible when it is activated?

**Comment by irsat000** [comment]
Utility menu has "hide memory riminders" checkbox. There is no automatic hiding of memories. I assume you mean the memories, not the messages.

**Comment by CashOver** [comment]
Yes, but it is about the messages that are left in the Memory Manager that can be hidden when the program is running. And you can also leave the messages saved in the Memory Manager for the next chat session, as it is always being deleted in the standard character.ai mode, not the old one. Fix the error with contact from the old version of the site, as it is giving an error when clicking on the Memory Manager.

**Comment by irsat000** [comment]
I didn't understand anything, I am sorry. You should practice English more or use the correct terms.

**Comment by CashOver** [comment]
It's the Firefox version...

**Comment by irsat000** [comment]
Make sure you are using v2.7.4. The previous 3 updates were buggy, each of them is a hotfix, it was a rough day lol.

Right now I only know of one problem with memory manager v2, but it won't cause any errors, since it's only about not inserting memories for bot response swipes.

I will test further when this is over to see the problems you mentioned.

But each chat's memories are saved separately now, if you are talking about that.

**Comment by CashOver** [comment]
Just to let you know, I'm using the new version, and thanks a lot for letting me know about this, but I'm aware of the bugs still in this version.

**Comment by irsat000** [comment]
Okay, I made plenty of adjustments and I think it's complete. If you tell me all the errors with exactly how they occur, I can fix those too.

**Comment by irsat000** [comment]
Are you still having issues about this topic?
