### ISSUE TITLE
memory manager issues

### ISSUE THREAD

**Issue by theapexfighter127** [irsat000/CAI-Tools#82]
I don't know id this is the right place to report this issue but here it goes.  

When I use it, it only affects the original replies. But its stops working when I edit them.

Also, it seems to work simply by throwing all the info we write in the memories into our own reply, which simply consumes tokens(?) and messes up the context and overall memory. (some times it even appears in my own reply and I have to edit it out)

That makes the memory manager mostly unusable on destktop. I don't know if that's just how it is and I'm not using it right, but I can't really use it most of the time.

Don't get me wrong, It's really nice but it's just not working well.

**Comment by irsat000** [comment]
This is for v2; Auto cleaning part means it will use the bare minimum of tokens. If it fails to auto clean, it might show up in your replies. In which case it will still be cleaned on the back end and bot will not see it.

When you edit your reply, in the UI there is no memory, because it's cleaned up visually.

Thanks for the feedback. I take 2 things from this;

First, I must check if cleaning up is working correctly. You can tell me in what cases this happens, maybe it's uncatched formatting caused by the memory you typed.

Second is that I might work on the editting so that it adds memories again.

Unfortunately this is the extent which us as the users can work on the chat system. It's a matter of access to back end and we don't have any.

**Comment by theapexfighter127** [comment]
Thank you for the reply. This extension really does wonders!

**Comment by irsat000** [comment]
I haven't seen the "first" problem. Does it still happen? You shouldn't see the v2 memory on screen ever.
