### ISSUE TITLE
[Question] What Are the Dummy Prompts for Chat Import?

### ISSUE THREAD

**Issue by JCollins2048** [irsat000/CAI-Tools#94]
I apologize if this isn't the right place for this, but I noticed something kind of funny, but kind of guilt-inducing.

Whenever a chat is imported, every single text box is edited.  This is entirely normal as this is the best way to import a chat wholesale.  However, when I "undo" the last edit, I see some funny messages.

- One 'bot said "you're driving me nuts".
- Another 'bot said "I'm literally going to block you now".
- Another still simply asked in OOCs, "(Can you please just tell me what that means?)"
- Finally, another 'bot rolled with it and seemed to indicate that my character was staring blankly into space.

Since edits of player posts aren't saved, it's impossible to see what was typed to generate the player's dummy posts and drive the bots into a frustration.  So, that got me wondering… **what _is_ being sent to the server on the player's behalf?**  Is it something interesting like "Dummy post"?  Something mundane like "…"?  Or simply nothing at all?  I must know!

Also, this chat export and import function is absolutely **amazing**.  Thank you for making it so easy to juggle chats between accounts, clone chats, and the like!

**Comment by irsat000** [comment]
First it fills the chat with "Shell messages", then edits them. Editing bot message doesn't overwrite the message but creates an another candidate.

It's creating message pairs first, by sending "(Shell message)" or something, I forgot the exact message. Before that I was using something like "Just say hello nothing else", so that it would keep the reply short to save time. It had no difference so I used this new simple Shell message text.

This is why the bot gets angry, you say the same thing over and over again lol.

Actually there is a bug that many people encounters with the new method. It's a total mystery but apparently it can't update which message is the selected one. So the original messages appear instead. Kinda embarrassing.

**Comment by JCollins2048** [comment]
Ah.  That sounds about right.  I actually back-traced a random imported conversation and the 'bot *did* mention something about a "shell message" message.  Good to know for trivia's sake!

As for the new bug, I sincerely wish I could help with that.  For better or worse, the amazing export-and-import features has never failed on me or even gotten stuck, and it always edits every single message correctly, for me.  The bug you mentioned might have to do with rate limits, or the current load on the server.  If I can find a relevant open Issue here, I'll give more thoughts on it.

Thank you for your answer, and thanks for continuing to update this queue of fantastic tools and features!
(Also, thanks for the early Christmas gift! Free premium for everyone until January is pretty awesome!)
