### ISSUE TITLE
Nothing downloads

### ISSUE THREAD

**Issue by bravekrab** [irsat000/CAI-Tools#95]
Cannot get characters to download a json from CAI. Clicking json in CAI tools does nothing. A lot of the features are not working. Clicking options does nothing. Tried on firefox and chrome.

**Comment by bravekrab** [comment]
Same issues as https://github.com/irsat000/CAI-Tools/issues/93

**Comment by bravekrab** [comment]
![Screenshot_20241215_175855](https://github.com/user-attachments/assets/263d28c2-e244-4d71-9571-fb639a7d837f)
![Screenshot_20241215_175940](https://github.com/user-attachments/assets/c70bbff5-a66d-4a87-8b01-703f0673aca4)

**Comment by irsat000** [comment]
Out of all bugs we experience, this one seems to be the strangest one. Because it's actually handled by website itself. It says plus.character.ai blocked character.ai. Like the character.ai is the one that uses plus.character.ai, only thing I could do here is take the code in a service worker to bypass the CORS policies of the browser.

Maybe it's the content script, okay, test this, when you are still having this issue, disable the CAI Tools, and create a character. If it creates the character, it's a problem with the extension.
