### ISSUE TITLE
Group chat major bug

### ISSUE THREAD

**Issue by 1Silverstorm23** [irsat000/CAI-Tools#97]
Hi after using the C AI tools in web for cloning someone's bot ( for the first time using the tools)then after that i run into problem when using the C AI app and that is in group chat that most of the bots original bots can't be added if i tried it show that.
**Sorry, something went wrong** please try again 
( Im just a new user of the tools and the GitHub so i could not help except report this bug sorry if my English is bad) I don't know if this was addressed before or if there's a warning for C AI app user's  

And also I don't know if this bug is for the tools or even for the apps

**Comment by irsat000** [comment]
"in group chat that most of the bots original bots can't be added if i tried it show that."

Could you repeat this?

For the error, it doesn't seem to be caused by the extension. Copying a character is no different than you simply creating a new character. There is nothing that could break the website here.

If you wanna be sure, disable the extension and try again. Then activate again, experiment. It should be a temporary bug on the website's end.

**Comment by 1Silverstorm23** [comment]
It's the app that i am using and for example the original bot name kilua if i try to add it in a group chat it won't allow except the cloned one from the tools which would be allowed

**Comment by irsat000** [comment]
So the difference is one is not your bot, and the new one is your bot.

I don't know about group chats. Maybe you can only use your own characters? You tell me.

**Comment by 1Silverstorm23** [comment]
Wait i found something in reddit it seems the group chat is not working well at the moment and i can see some post the same and i can by pass it by using the cloned one by the tools it's seemed i made a false alarm

**Comment by irsat000** [comment]
I will close these issues as completed. They are caused by the servers.

**Comment by 1Silverstorm23** [comment]
Okay thanks by the way

**Comment by irsat000** [comment]
No problem. When in doubt, you can always disable extension to see if it's the issue.
